# Morphic for Windows (.NET Desktop)

# Documentation used in this pipeline:
# .NET pipelines docs: 
# - Build, test, and deploy: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core
# - .NET pipelines tasks: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/
# Microsoft-hosted agents: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
# - Windows 2019 components and version options: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
# .NET Core release versions: https://github.com/dotnet/core/blob/main/release-notes/releases-index.json
# .NET Core RIDs (including x86/x64/ARM64): https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

trigger:
  branches:
    include:
    # TODO: before production, limit the branches that are automatically built
#      - master
      - '*'

pr:
  branches:
    include:
    - '*'
    
pool:
  vmImage: 'windows-2019'

variables:
- name: mainProject
  value: Morphic/Morphic.csproj
- name: projects
  value:  |
      Morphic.Core/Morphic.Core.csproj
      Morphic.OAuth/Morphic.OAuth.csproj
      Morphic.Windows.Native/Morphic.Windows.Native.csproj
      Morphic/Morphic.csproj
  
  # TODO: temporary values
- name: versionMajor
  value: 1
- name: versionMinor
  value: 9
- name: versionBuild
  value: 10
- name: versionRevision
  value: 0

stages:
  - stage: build
    jobs:
      - job: build
        steps:
        - task: UseDotNet@2
          displayName: "Use .NET SDK 6.0-preview.1"
          inputs:
            packageType: sdk
            version: 6.0.100-preview.1.21103.13
            installationPath: $(Agent.ToolsDirectory)/dotnet

        - task: CmdLine@2
          inputs:
            script: 'dotnet --info'

        - task: DotNetCoreCLI@2
          displayName: "dotnet restore"
          inputs:
            command: restore
            projects: '$(projects)'
        
        - task: DotNetCoreCLI@2
          displayName: "dotnet build"
          inputs:
           command: build
           projects: '$(mainProject)'

        - task: DotNetCoreCLI@2
          displayName: "dotnet publish (x86)"
          inputs:
            command: publish
            publishWebProjects: false
            projects: '$(mainProject)'
            arguments: '-f net6.0-windows -r win10-x86 -c Release'


        - task: DotNetCoreCLI@2
          displayName: "dotnet publish (x64)"
          inputs:
            command: publish
            publishWebProjects: false
            projects: '$(mainProject)'
            arguments: '-f net6.0-windows -r win10-x64 -c Release'


        - task: DotNetCoreCLI@2
          displayName: "dotnet publish (arm64)"
          inputs:
            command: publish
            publishWebProjects: false
            projects: '$(mainProject)'
            arguments: '-f net6.0-windows -r win10-arm64 -c Release'

        - powershell: |
            # Update MorphicPackage's appmanifest with a version number before building it
            [xml]$manifest= get-content ".\MorphicPackage\Package.appxmanifest"
            $manifest.Package.Identity.Version = "$(versionMajor).$(versionMinor).$(versionBuild).$(versionRevision)"    
            $manifest.save("MorphicPackage/Package.appxmanifest")
          displayName: 'Assign version to package manifest'

        - task: MSBuild@1
          displayName: "package msix (x86)"
          inputs:
            solution: MorphicPackage/MorphicPackage.wapproj
            msbuildVersion: 16.9.0-preview-21103-02+198f3f262
            platform: x86
            configuration: Release
            msbuildArguments: '/p:OutputPath=NonPackagedApp /p:UapAppxPackageBuildMode=SideLoadOnly  /p:AppxBundle=Never /p:AppxPackageOutput=$(Build.ArtifactStagingDirectory)\MorphicSetup_x86.msix /p:AppxPackageSigningEnabled=false'

        - task: MSBuild@1
          displayName: "package msix (x64)"
          inputs:
            solution: MorphicPackage/MorphicPackage.wapproj
            msbuildLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\'
            platform: x64
            configuration: Release
            msbuildArguments: '/p:OutputPath=NonPackagedApp /p:UapAppxPackageBuildMode=SideLoadOnly  /p:AppxBundle=Never /p:AppxPackageOutput=$(Build.ArtifactStagingDirectory)\MorphicSetup_x64.msix /p:AppxPackageSigningEnabled=false'

        - task: MSBuild@1
          displayName: "package msix (arm64)"
          inputs:
            solution: MorphicPackage/MorphicPackage.wapproj
            msbuildVersion: 16.9.0-preview-21103-02+198f3f262
            platform: arm64
            configuration: Release
            msbuildArguments: '/p:OutputPath=NonPackagedApp /p:UapAppxPackageBuildMode=SideLoadOnly  /p:AppxBundle=Never /p:AppxPackageOutput=$(Build.ArtifactStagingDirectory)\MorphicSetup_arm64.msix /p:AppxPackageSigningEnabled=false'
