# Morphic for Windows (.NET Desktop)

# Documentation used in this pipeline:
# .NET pipelines docs: 
# - Build, test, and deploy: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core
# - .NET pipelines tasks: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/
# Microsoft-hosted agents: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
# - Windows 2019 components and version options: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
# .NET Core release versions: https://github.com/dotnet/core/blob/main/release-notes/releases-index.json
# .NET Core RIDs (including x86/x64/ARM64): https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
    - '*'
    
pool:
  vmImage: 'windows-2019'

variables:
- name: solution
  value: Morphic.sln
- name: projects
  value:  |
      Morphic.Core/Morphic.Core.csproj
      Morphic.OAuth/Morphic.OAuth.csproj
      Morphic.Windows.Native/Morphic.Windows.Native.csproj
      Morphic/Morphic.csproj

stages:
  - stage: build
    jobs:
      - job: build
        steps:
        - task: UseDotNet@2
          displayName: "Use .NET SDK 6.0-preview.1"
          inputs:
            packageType: sdk
            version: 6.0.100-preview.1.21103.13
            installationPath: $(Agent.ToolsDirectory)/dotnet

        - task: DotNetCoreCLI@2
          displayName: "restore projects"
          inputs:
	    command: restore
	    projects: '$(projects)'
        
        - task: DotNetCoreCLI@2
          displayName: "build projects"
          inputs:
	    command: build
	    projects: '$(projects)'
        
        - task: DotNetCoreCLI@2
          displayName: "build solution"
          inputs:
	    command: build
	    projects: '$(solution)'
        
